import type { Metric } from "../domain/types";

export const METRICS: Metric[] = [
  {
    id: "activation_rate",
    name: "Activation rate",
    category: "revenue",
    type: "leading",
    definition: "Persentase user baru yang mencapai milestone aktivasi.",
    formula: "activated_users / new_users",
    defaultEstimationMethod: "benchmark",
    dataRequirements: ["New users", "Activated users (milestone definition)"],
  },
  {
    id: "feature_adoption_rate",
    name: "Feature adoption rate",
    category: "strategic",
    type: "leading",
    definition: "Persentase user yang menggunakan fitur dalam window tertentu.",
    formula: "users_used_feature / eligible_users",
    defaultEstimationMethod: "benchmark",
    dataRequirements: ["Eligible users", "Users who used the feature"],
  },
  {
    id: "retention_d30",
    name: "Retention (D30) proxy",
    category: "revenue",
    type: "lagging",
    definition: "Persentase cohort yang masih aktif di hari ke-30 (proxy).",
    formula: "active_day30_users / cohort_users",
    defaultEstimationMethod: "benchmark",
    dataRequirements: ["Cohort size", "Active users at day 30"],
  },
  {
    id: "conversion_rate",
    name: "Conversion rate (flow)",
    category: "revenue",
    type: "lagging",
    definition: "Persentase user yang menyelesaikan step kunci dalam funnel/flow.",
    formula: "completions / entrants",
    defaultEstimationMethod: "benchmark",
    dataRequirements: ["Flow entrants", "Flow completions"],
  },
  {
    id: "abandonment_rate",
    name: "Abandonment rate",
    category: "revenue",
    type: "leading",
    definition: "Persentase user yang drop sebelum menyelesaikan flow.",
    formula: "1 - completion_rate",
    defaultEstimationMethod: "benchmark",
    dataRequirements: ["Flow entrants", "Flow completions"],
  },
  {
    id: "task_success_rate",
    name: "Task success rate",
    category: "strategic",
    type: "leading",
    definition: "Persentase user yang berhasil menyelesaikan task tanpa gagal.",
    formula: "successful_tasks / attempts",
    defaultEstimationMethod: "baseline",
    dataRequirements: ["Task attempts", "Successful tasks"],
  },
  {
    id: "time_on_task",
    name: "Time-to-complete task",
    category: "cost",
    type: "leading",
    definition: "Rata-rata waktu yang dibutuhkan user untuk menyelesaikan task.",
    formula: "avg(task_duration_seconds)",
    defaultEstimationMethod: "baseline",
    dataRequirements: ["Task duration telemetry (or usability study)"],
  },
  {
    id: "support_tickets",
    name: "Support tickets (volume)",
    category: "cost",
    type: "lagging",
    definition: "Jumlah tiket support terkait flow/masalah per window.",
    defaultEstimationMethod: "baseline",
    dataRequirements: ["Ticket count tagged to topic/flow"],
  },
  {
    id: "incident_count",
    name: "Incidents per month",
    category: "risk",
    type: "lagging",
    definition: "Jumlah incident (Sev-based) per bulan.",
    defaultEstimationMethod: "baseline",
    dataRequirements: ["Incident logs, severity classification"],
  },
  {
    id: "mttr",
    name: "MTTR (proxy)",
    category: "risk",
    type: "lagging",
    definition: "Mean time to restore/recover (proxy).",
    defaultEstimationMethod: "baseline",
    dataRequirements: ["Incident restore timestamps"],
  },
  {
    id: "maintenance_time_pct",
    name: "% engineering time on maintenance",
    category: "cost",
    type: "leading",
    definition: "Persentase waktu tim yang dipakai untuk maintenance/bug/ops.",
    defaultEstimationMethod: "assumption",
    dataRequirements: ["Team size", "Work allocation estimate"],
  },
  {
    id: "lead_time_changes",
    name: "Lead time for changes (proxy)",
    category: "cost",
    type: "leading",
    definition: "Waktu dari mulai kerja sampai change production (proxy).",
    defaultEstimationMethod: "benchmark",
    dataRequirements: ["PR cycle time or deployment timestamps"],
  },
  {
    id: "defect_escape_rate",
    name: "Defect escape rate (proxy)",
    category: "risk",
    type: "lagging",
    definition: "Proporsi defect yang lolos ke production (proxy).",
    defaultEstimationMethod: "benchmark",
    dataRequirements: ["Bugs found in prod vs pre-prod"],
  },
  {
    id: "compliance_gap_count",
    name: "Compliance gap count",
    category: "risk",
    type: "leading",
    definition: "Jumlah gap/temuan compliance yang belum ditutup.",
    defaultEstimationMethod: "baseline",
    dataRequirements: ["Checklist/audit findings"],
  },
  {
    id: "audit_readiness",
    name: "Audit readiness (checklist completion)",
    category: "strategic",
    type: "leading",
    definition: "Persentase checklist audit yang sudah terpenuhi.",
    formula: "completed_items / total_items",
    defaultEstimationMethod: "baseline",
    dataRequirements: ["Audit checklist"],
  },
  {
    id: "wcag_issues_sev",
    name: "Accessibility issues by severity (WCAG)",
    category: "risk",
    type: "leading",
    definition: "Jumlah issue accessibility dikelompokkan berdasarkan severity.",
    defaultEstimationMethod: "baseline",
    dataRequirements: ["Accessibility audit results"],
  },
  {
    id: "engagement_dau_wau",
    name: "DAU/WAU (engagement)",
    category: "strategic",
    type: "leading",
    definition: "Rasio daily active users terhadap weekly active users.",
    formula: "DAU / WAU",
    defaultEstimationMethod: "benchmark",
    dataRequirements: ["DAU", "WAU"],
  },
  {
    id: "retention_proxy",
    name: "Retention proxy",
    category: "revenue",
    type: "lagging",
    definition: "Proxy retention sesuai konteks (D7/D30/Repeat usage).",
    defaultEstimationMethod: "benchmark",
    dataRequirements: ["Cohort definition", "Return usage"],
  },
];

export function getMetric(metricId: string) {
  return METRICS.find((m) => m.id === metricId);
}

